INSERT INTO protein (id, name, gram, quant) VALUES (1, 'FRANGO', 150, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (2, 'FRANGO', 120, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (3, 'FRANGO', 100, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (4, 'FRANGO', 70, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (5, 'FRANGO', 50, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (6, 'COXAO MOLE', 150, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (7, 'COXAO MOLE', 120, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (8, 'COXAO MOLE', 50, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (9, 'CAMARAO', 100, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (10, 'CAMARAO', 70, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (11, 'CAMARAO', 50, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (12, 'TILAPIA', 150, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (13, 'TILAPIA', 100, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (14, 'MAMINHA', 150, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (15, 'CARNE DE SOL', 150, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (16, 'CARNE DE SOL', 70, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (17, 'CARNE DE SOL', 20, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (18, 'PICANHA SUINA', 150, 0);
INSERT INTO protein (id, name, gram, quant) VALUES (19, 'CALABRESA', 30, 0);